#!/bin/bash

# Fungsi untuk mengirim log ke Telegram
function send_log() {
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    TIME="10"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIFICATIONS MULTI LOGIN ⚠️</b>
<code>────────────────────</code>
<code>Username  : </code><code>$user</code>
<code>Limit Ip  : </code><code>$iplimit</code>
<code>────────────────────</code>
"
    curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

# Fungsi untuk membatasi IP pada VMess
function vmip() {
    echo -n > /var/log/xray/access.log
    sleep 440
    data=( $(ls /etc/kyt/limit/vmess/ip) )

    for user in "${data[@]}"; do
        iplimit=$(cat /etc/kyt/limit/vmess/ip/$user)
        active_ips=$(grep "$user" /var/log/xray/access.log | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq)
        ip_count=$(echo "$active_ips" | wc -l)

        if [[ $ip_count -gt $iplimit ]]; then
            exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
            sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
            sed -i "/^### $user $exp/d" /etc/vmess/.vmess.db
            systemctl restart xray >/dev/null 2>&1
            rm -rf /etc/kyt/limit/vmess/ip/$user
            send_log
        fi
        sleep 0.1
    done
}

# Fungsi untuk membatasi IP pada VLess
function vlip() {
    echo -n > /var/log/xray/access.log
    sleep 440
    data=( $(ls /etc/kyt/limit/vless/ip) )

    for user in "${data[@]}"; do
        iplimit=$(cat /etc/kyt/limit/vless/ip/$user)
        active_ips=$(grep "$user" /var/log/xray/access.log | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq)
        ip_count=$(echo "$active_ips" | wc -l)

        if [[ $ip_count -gt $iplimit ]]; then
            exp=$(grep -w "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
            sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
            sed -i "/^#& $user $exp/d" /etc/vless/.vless.db
            systemctl restart xray >/dev/null 2>&1
            rm -rf /etc/kyt/limit/vless/ip/$user
            send_log
        fi
        sleep 0.1
    done
}

# Fungsi untuk membatasi IP pada Trojan
function trip() {
    echo -n > /var/log/xray/access.log
    sleep 440
    data=( $(ls /etc/kyt/limit/trojan/ip) )

    for user in "${data[@]}"; do
        iplimit=$(cat /etc/kyt/limit/trojan/ip/$user)
        active_ips=$(grep "$user" /var/log/xray/access.log | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq)
        ip_count=$(echo "$active_ips" | wc -l)

        if [[ $ip_count -gt $iplimit ]]; then
            exp=$(grep -w "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
            sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
            sed -i "/^#! $user $exp/d" /etc/trojan/.trojan.db
            systemctl restart xray >/dev/null 2>&1
            rm -rf /etc/kyt/limit/trojan/ip/$user
            send_log
        fi
        sleep 0.1
    done
}

# Menjalankan fungsi berdasarkan argumen
case "$1" in
    "vmip")
        vmip
        ;;
    "vlip")
        vlip
        ;;
    "trip")
        trip
        ;;
    *)
        echo "Usage: $0 {vmip|vlip|trip}"
        exit 1
        ;;
esac
